### ISSUE TITLE
Bug: table_cols List Index out of range

### ISSUE THREAD

**Issue by will-moore** [ome/omero-parade#104]
From https://www.openmicroscopy.org/qa2/qa/feedback/31187/

```
Traceback (most recent call last):

File "/opt/omero/venv_web/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/opt/omero/venv_web/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/venv_web/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/opt/omero/venv_web/lib64/python3.6/site-packages/omero_parade/views.py", line 128, in filter_script
return module.get_script(request, filter_name, conn)

File "/opt/omero/venv_web/lib64/python3.6/site-packages/omero_parade/csv_filters/omero_filters.py", line 194, in get_script
'default': table_cols[0],

IndexError: list index out of range
```

**Comment by will-moore** [comment]
Reported again at https://www.openmicroscopy.org/qa2/qa/feedback/32652/
