### ISSUE TITLE
csv_filters IndexError: list index out of range for table_cols

### ISSUE THREAD

**Issue by will-moore** [ome/omero-parade#130]
Haven't looked into this but looks like no `table_cols` are found in a csv, giving an IndexError...
Reported at https://www.openmicroscopy.org/qa2/qa/feedback/40337/

```
Traceback (most recent call last):

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_parade/views.py", line 128, in filter_script
return module.get_script(request, filter_name, conn)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_parade/csv_filters/omero_filters.py", line 194, in get_script
'default': table_cols[0],

IndexError: list index out of range
```

**Comment by will-moore** [comment]
Related but different error at https://www.openmicroscopy.org/qa2/qa/feedback/42083/

```
Traceback (most recent call last):

File "/opt/omero/web/venv3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)

File "/opt/omero/web/venv3/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv3/lib/python3.10/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib/python3.10/site-packages/omero_parade/views.py", line 182, in get_data
data = module.get_data(request, data_name, conn)

File "/opt/omero/web/venv3/lib/python3.10/site-packages/omero_parade/csv_filters/data_providers.py", line 113, in get_data
img_id = row[img_col_idx].strip()

IndexError: list index out of range
```
