### ISSUE TITLE
Add table data combobox

### ISSUE THREAD

**Issue by jburel** [ome/omero-parade#21]
* log in as user-1 on web-dev-merge
* select ``archiveddv``
* In parade:Select in combobox "Add table Data" the ``ROI count`` option
```
Traceback (most recent call last):

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/WEB-DEV-merge-deploy/OMERO.py/lib/python/omeroweb/decorators.py", line 483, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/omero_parade/views.py", line 181, in get_data
    'histogram': list(histogram)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/http/response.py", line 535, in __init__
    data = json.dumps(data, cls=encoder)

  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)

  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/serializers/json.py", line 115, in default
    return super(DjangoJSONEncoder, self).default(o)

  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

TypeError: 6 is not JSON serializable


<WSGIRequest
path:/omero_parade/data/Uk9JX2NvdW50/,
GET:<QueryDict: {u'_': [u'1524141990109'], u'dataset': [u'1457']}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.74430613.1492428942',
 '_gid': 'GA1.2.1403166767.1524053537',
 'csrftoken': 'FojPGWicIBZJrzOBiUS03HPIRxsM73I2',
 'phpbb3_a9mfv_k': '',
 'phpbb3_a9mfv_sid': 'a419d989a95ebbcf51915de7ed5a1532',
 'phpbb3_a9mfv_u': '1',
 'sessionid': '5x7euiyxys7eoel6p62qapoa126myv19',
 'style_cookie': 'null'},
META:{u'CSRF_COOKIE': u'FojPGWicIBZJrzOBiUS03HPIRxsM73I2',
 'HTTP_ACCEPT': 'application/json, text/javascript, */*; q=0.01',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9,fr;q=0.8',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': '_ga=GA1.2.74430613.1492428942; csrftoken=FojPGWicIBZJrzOBiUS03HPIRxsM73I2; phpbb3_a9mfv_k=; style_cookie=null; phpbb3_a9mfv_u=1; phpbb3_a9mfv_sid=a419d989a95ebbcf51915de7ed5a1532; sessionid=5x7euiyxys7eoel6p62qapoa126myv19; _gid=GA1.2.1403166767.1524053537',
 'HTTP_HOST': 'web-dev-merge.openmicroscopy.org',
 'HTTP_REFERER': 'http://web-dev-merge.openmicroscopy.org/webclient/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '134.36.162.209',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
 'PATH_INFO': u'/omero_parade/data/Uk9JX2NvdW50/',
 'QUERY_STRING': 'dataset=1457&_=1524141990109',
 'RAW_URI': '/omero_parade/data/Uk9JX2NvdW50/?dataset=1457&_=1524141990109',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '49318',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': '127.0.0.1',
 'SERVER_PORT': '4080',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/19.7.1',
 'gunicorn.socket': <socket._socketobject object at 0x725b980>,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x690f890>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x690fb10>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

cc @will-moore @emilroz @chris-allan

**Comment by jburel** [comment]
see https://github.com/ome/omero-parade/pull/33
