### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by ppouchin** [ome/omero-parade#82]
It seems that when table columns have a "µ" in their name, OMERO.parade is not able to use them for graphs. 
These tables are come from a Fiji Jython script where the results are saved as tables, like [this one in Groovy](https://github.com/ome/training-scripts/blob/master/practical/groovy/analyse_dataset_save_rois_and_summary_table.groovy). Maybe there is something to do there I guess?

The following error appears: 

```
Traceback (most recent call last):

  File "/omero/.virtualenvs/web/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)

  File "/omero/.virtualenvs/web/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)

  File "/omero/.virtualenvs/web/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/omero/.virtualenvs/web/lib/python3.7/site-packages/omeroweb/decorators.py", line 538, in wrapped
    retval = f(request, *args, **kwargs)

  File "/omero/.virtualenvs/web/lib/python3.7/site-packages/omero_parade/views.py", line 172, in get_data
    data_name = data_name.decode('utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 23: invalid start byte
```

**Comment by will-moore** [comment]
Reported again at https://www.openmicroscopy.org/qa2/qa/feedback/30899/
